name: 同步Release
on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 同步所有 Releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SRC: SuperMonster003/AutoJs6
          DST: ${{ github.repository }}
        run: |
          sudo apt install -y gh jq
          
          # 克隆原项目 releases
          gh release list --repo $SRC | awk '{print $1}' | while read tag; do
            echo "同步 $tag..."
            
            # 下载
            gh release download "$tag" --repo $SRC --dir ./files --clobber
            
            # 上传
            gh release create "$tag" ./files/* --repo $DST \
              --title "$tag" \
              --notes "同步自上游 $SRC" \
              --clobber
              
            rm -rf ./files
          done
